version: '3'

services:

  	mongodb:
		image: 'mongo'
		container_name: JSPF-Mongo
		volumes:
		- './docker/data/mongodb:/data/db'
		ports:
		- '27017:27017'

	redis:
		image: redis
		volumes:
		- './docker/data/redis:/data'
		ports:
		- "6379:6379"

  	server:
		build:
			context: ./
			dockerfile: Dockerfile
		container_name: JSPF-Server
		volumes:
      	- ./docker/storage:/usr/src/app/storage
		env_file:
		- .env
		ports:
		- '5000:5000'
		- '8000:8000'
		depends_on:
		- mongodb
		- redis