version: '3'

services:
  nginx:
    image: nginx:1.12.2
    container_name: jspf_nginx
    depends_on:
    - node_app
    volumes:
    - ./docker/nginx:/etc/nginx/conf.d
    - ./docker/logs:/var/log/nginx
    restart: always
    # ports:
    # - "6800:80"

  redis:
    image: redis:3.0-alpine
    container_name: jspf-redis
    command: redis-server
    volumes:
    - './docker/data/redis:/data'
    ports:
    - "6379:6379"

  mongodb:
    image: 'mongo'
    container_name: jspf-mongo
    volumes:
    - './docker/data/mongodb:/data/db'
    ports:
    - '27017:27017'

  node_app:
    build:
      context: ./
      dockerfile: ./docker/build_files/Dockerfile
    container_name: jspf-server
    restart: always
    volumes:
        - ./docker/storage:/usr/src/app/storage
    ports:
    - '5000:5000'
    - '8000:8000'
    depends_on:
    - mongodb
    - redis