version: '3.7'

services:

  mongodb:
	image: 'mongo'
	container_name: JSPF-Mongo
	volumes:
    - '/data/mongodb/db:/data/db'
	ports:
	- '27017:27017'

  server:
	build:
		context: ./JSPF-Server
		dockerfile: Dockerfile
	container_name: JSPF-Server
	env_file:
	- .env
	ports:
	- '8000:8000'
	links:
	- mongodb
	depends_on:
	- mongodb

  client:
	build:
		context: ./JSPF-Web
		dockerfile: Dockerfile
	container_name: JSPF-Web
	env_file:
	- .env
	ports:
	- '3000:3000'
	depends_on:
	- server